### ISSUE TITLE
Proxy does not permit monkey-patching instances or objects

### ISSUE THREAD

**Issue by Senney** [rmagatti/auto-logger#6]
## Issue

When attempting to write unit tests for classes which are wrapped with autoreggol, we attempted to apply a spy to one of the member methods of the class. The application of the spy was intercepted by autoreggol and was discarded.

## Minimal repro

Code sandbox: https://codesandbox.io/s/rough-sun-3i5tsu

I think the Proxy should be updated to permit monkey-patching, but there might be some extra considerations that I haven't thought of - Maybe re-wrapping monkey-patched functions with the logger?

**Comment by rmagatti** [comment]
Hey @Senney, yeah this makes sense, the proxy essentially isn't passing whatever the spy does through. I _think_ just doing what you mention should work, I can't immediately think of why that would cause a problem, could be worth releasing a beta version of this library to test it out and maybe validate other cases haven't broken. Feel free to submit a PR if you've got some time, otherwise, I'll try and get to it sometime next week! 👍
